alternative datapath patch
grasmanek94/darkreign2 pull request #2
Opened 2017-06-06 10:12 UTC by Rurigan

Enables use of alternatve data path by setting the environment string: dr2data. If this string exist and is not empty the initializationcode simply changes the current working director to this path.  A patch in the sound module was also nessary to make the mss system load from selected path

2017-06-06 18:38 UTC, grasmanek94 commented
Hm one question if I might ask: what are the advantages of doing this over `cd`'ing to a directory and using the full path to the .exe? e.g.:

    C:\> cd /d D:\MyDr2Data
    D:\MyDr2Data> D:\Games\DarkReign2\dr2.exe

2017-06-06 18:42 UTC, grasmanek94 commented on graphics/vid.cpp
> +      S32 l = (GetSystemMetrics(SM_CXSCREEN) - width)  >> 1;
This won't work for a multi-monitor setup, DR2 allows to choose which monitor you want the game to run on. Maybe its best to leave as-is or rewrite and test for multi monitor setups (so it centers on the selected screen by the user).

2017-06-06 18:48 UTC, grasmanek94 requested changes
https://github.com/grasmanek94/darkreign2/pull/2/commits/caf55a1ea555002dfb3ddcd6a75374f075657e06

This won't work for a multi-monitor setup, DR2 allows to choose which monitor you want the game to run on. Maybe its best to leave as-is or rewrite and test for multi monitor setups (so it centers on the selected screen by the user).

2017-06-06 19:06 UTC, Rurigan commented
bat file will maybe work ok if it knows the path to the exe. I don't find environment string less use full on windows as on linux or any other platform. It is a way to separate the data from the exe.  I would like to have put it on the command line. But the code that execute before the command line is processed needs to know the root path

2017-06-06 19:11 UTC, Rurigan commented
The center code only execute when it runs in windowed mode. An then other code will always put that window on the main desktop. It is a bug I corrected - not a feature added.

2017-06-07 11:43 UTC, Rurigan commented
Well it is your choice. That was always a bug that annoyed me. I will keep
it since I alway run in windowed mode when I start dr2 in the debugging
environment. And again! That particular code only execute when you go into
windowed mode. And the code execute before or after these two corrected
lines are the code that place the window on the main monitor.

Have you tested it with a two monitor setup?



2017-06-06 20:48 GMT+02:00 Gamer_Z <notifications@github.com>:

> *@grasmanek94* requested changes on this pull request.
>
> This won't work for a multi-monitor setup, DR2 allows to choose which
> monitor you want the game to run on. Maybe its best to leave as-is or
> rewrite and test for multi monitor setups (so it centers on the selected
> screen by the user).
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/grasmanek94/darkreign2/pull/2#pullrequestreview-42411634>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/AXkyoeTV8rB4s6fEjwnTKwHNORA7llx3ks5sBZ74gaJpZM4NxIfs>
> .
>

2017-06-07 11:51 UTC, Rurigan commented
I forgot to mention. It tested your bat suggestion. It don't work! Try it
with the first JDA campaign and you will notice that some of the sound is
missing from the sequence where the shuttle is crashing.

And by the way. Windows relies heavily on environment strings. That is why
there are still there and will be there in the future. For one thing it is
good for passing parameters to the application it can access before the
command line is processed. It is part of the processes environment so to
say.

2017-06-07 13:43 GMT+02:00 Søren Amtorp <sa19620821@gmail.com>:

> Well it is your choice. That was always a bug that annoyed me. I will keep
> it since I alway run in windowed mode when I start dr2 in the debugging
> environment. And again! That particular code only execute when you go into
> windowed mode. And the code execute before or after these two corrected
> lines are the code that place the window on the main monitor.
>
> Have you tested it with a two monitor setup?
>
>
>
> 2017-06-06 20:48 GMT+02:00 Gamer_Z <notifications@github.com>:
>
>> *@grasmanek94* requested changes on this pull request.
>>
>> This won't work for a multi-monitor setup, DR2 allows to choose which
>> monitor you want the game to run on. Maybe its best to leave as-is or
>> rewrite and test for multi monitor setups (so it centers on the selected
>> screen by the user).
>>
>> —
>> You are receiving this because you authored the thread.
>> Reply to this email directly, view it on GitHub
>> <https://github.com/grasmanek94/darkreign2/pull/2#pullrequestreview-42411634>,
>> or mute the thread
>> <https://github.com/notifications/unsubscribe-auth/AXkyoeTV8rB4s6fEjwnTKwHNORA7llx3ks5sBZ74gaJpZM4NxIfs>
>> .
>>
>
>

2017-06-12 12:11 UTC, grasmanek94 commented
> I forgot to mention. It tested your bat suggestion. It don't work

Hm could you give the steps to reproduce? For me everything worked fine while I tested it (campaign, instant game, multiplayer/lan). I would like to identify what's causing different behaviour.

2017-06-12 15:04 UTC, Rurigan commented
line 46 in sound.cpp...  it is a path passed to a dll that don't know the
main application have changed its working directory.
Any way it is no big deal and I have an other project that takes all my
attention.

But nice to see how smooth the game is running after so many years. I am
happy playing it now and them. And now even with the window not correct
correct centred at startup bug.

I am getting used to Git. Nice way to backup your work and even being able
to roll back and all the other stuff.



2017-06-12 14:11 GMT+02:00 Gamer_Z <notifications@github.com>:

> I forgot to mention. It tested your bat suggestion. It don't work
>
> Hm could you give the steps to reproduce? For me everything worked fine
> while I tested it (campaign, instant game, multiplayer/lan). I would like
> to identify what's causing different behaviour.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/grasmanek94/darkreign2/pull/2#issuecomment-307771368>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/AXkyoSRxpy6_nGA2_UG8VxveJfkU1Jbdks5sDSr6gaJpZM4NxIfs>
> .
>

2024-06-29 23:41 UTC, closed without merging